// <auto-generated />
using MYAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MYAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260426144142_Intrest-Links")]
    partial class IntrestLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MYAPI.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The act of writing code and developing a product/application",
                            Title = "Programing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Listening or creating music",
                            Title = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Playing or Creating Games",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Completing a task/game as fast as you can",
                            Title = "Speedrunning"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Creating delicious food",
                            Title = "Cooking"
                        });
                });

            modelBuilder.Entity("MYAPI.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1,
                            URL = "https://www.w3schools.com/"
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            PersonId = 1,
                            URL = "https://open.spotify.com/"
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 3,
                            PersonId = 2,
                            URL = "https://steamcommunity.com/id/RasmusFPS/"
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 4,
                            PersonId = 3,
                            URL = "https://www.speedrun.com/users/RasmusFPS/"
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 5,
                            PersonId = 4,
                            URL = "https://www.arla.se/recept/"
                        });
                });

            modelBuilder.Entity("MYAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Malte Andersson",
                            Phone_Number = "070-000-0000"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Max Granqvist",
                            Phone_Number = "070-000-0000"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ben Thomasson",
                            Phone_Number = "070-000-0000"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rasmus Andersen",
                            Phone_Number = "070-000-0000"
                        });
                });

            modelBuilder.Entity("MYAPI.Models.Link", b =>
                {
                    b.HasOne("MYAPI.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MYAPI.Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MYAPI.Models.Person", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
